name: Bandit

on:
  push:
  pull_request: 

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v6

    - name: Python version
      uses: actions/setup-python@v5

    - name: Install Bandit
      run: pip install bandit

    - name: run bandit
      run: bandit -r
